FROM quay.io/wildfly/wildfly:latest-jdk17

USER root

ADD https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.2/postgresql-42.6.2.jar /opt/jboss/wildfly/postgresql.jar
COPY init-datasource.cli /opt/jboss/wildfly/init-datasource.cli

RUN /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/wildfly/init-datasource.cli

COPY ejb-module/target/ejb-module-1.0.0.jar /opt/jboss/wildfly/standalone/deployments/
COPY backend-module/target/backend-module.war /opt/jboss/wildfly/standalone/deployments/

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]